version: '3.3'
services:
  frontend:
    build: 
      context: ../../launc-frontend
      dockerfile: Dockerfile-local
    volumes:
      - '../../launc-frontend:/usr/src/app' 
    ports: 
      - '4200:4200'
    networks:
      - frontend

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=launc
      - POSTGRES_USER=launc
      - POSTGRES_PASSWORD=launc
    networks:
      - backend

  backend:
    build:
      context: ../../launc-backend
      dockerfile: Dockerfile-local
    volumes:
      - type: bind
        source: ../../launc-backend
        target: /app
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - database

networks:
  frontend: {}
  backend: {}
