version: '3.3'
services:
  frontend:
    build: 
      context: ../../launc-frontend
      dockerfile: Dockerfile-local
    volumes:
      - ../../launc-frontend:/app
    ports: 
      - '4200:4200'
    networks:
      - frontend

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=launc
      - POSTGRES_USER=launc
      - POSTGRES_PASSWORD=launc
    ports:
      - "5432:5432" # So we can connect to a remote database
    networks:
      - backend

  backend:
    build:
      context: ../../launc-backend
      dockerfile: Dockerfile-local
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - database

networks:
  frontend: {}
  backend: {}
