version: '3.7'
services:
  webserver:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites/:/etc/nginx/sites-available
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443

networks:
  backend: {}
  frontend: {}
