version: '3.3'
services:
  webserver:
    image: nginx:latest
    volumes:
      - ./static/:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites/:/etc/nginx/sites-available
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
  
  backend:
    image: joeyderuiter/launc-backend:release
    networks:
      - backend

  frontend:
    image: joeyderuiter/launc-frontend:release
    networks:
      - frontend

networks:
  backend: {}
  frontend: {}
