version: '3.3'
services:
  webserver:
    image: nginx:latest
    volumes:
      - ./static/:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites/:/etc/nginx/sites-available
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
  
  backend:
    image: joeyderuiter/launc-backend:release
    networks:
      - backend
    environment:
      - ASPNETCORE_URLS=http://+:80
      - LAUNC_DB_HOST=${CONN_HOST}
      - LAUNC_DEFAULT_CONNECTION_STRING=${CONN_STRING}
      - MOLLIE_REDIRECT_URL=http://launc.space/payment
      - MOLLIE_WEBHOOK_URL=http://api.launc.space/payment/webhook

  frontend:
    image: joeyderuiter/launc-frontend:release
    networks:
      - frontend

networks:
  backend: {}
  frontend: {}
